apiVersion: v1
kind: Service
metadata:
  name: hello-gke
  labels:
    app: hello-gke
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 9100
    targetPort: 8080
    name: metrics
  selector:
    app: hello-gke
