name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn package -DskipTests

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USER }}/hello-gke:${{ github.sha }} .

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Push image
      run: docker push ${{ secrets.DOCKER_USER }}/hello-gke:${{ github.sha }}

    - name: Update Kubernetes Manifest
      run: |
        sed -i "s|IMAGE_PLACEHOLDER|${{ secrets.DOCKER_USER }}/hello-gke:${{ github.sha }}|g" k8s/deployment.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add k8s/deployment.yaml
        git commit -m "Update image to ${{ github.sha }}"
        git push

